### ISSUE TITLE
Application Crashes when getting feedback on a page that has a Javascript Google Map

### ISSUE THREAD

**Issue by mollyfud** [Telerik-Verified-Plugins/Telerik-AppFeedback#1]
From doing testing, I have an app that uses a Google Map on a view which I build with the Google Map JavaScript api. After adding AppFeedback, taking feedback of the page with the map, the whole app crashes when you click the "Send Feedback" button. 

In the same app, if you are on a non-map page, the feedback is set fine. 

When I have a moment, I will try to create a reproducible project for this.

**Comment by mollyfud** [comment]
Export of a project with the issue available here: https://drive.google.com/file/d/0B_NLhoIdMc-sOEZXWkRKVUtUY0U/view?usp=sharing

If you just want to see the issue, a link to the Companion app version of the built project available here:
https://platform.telerik.com/appbuilder/Mist/MobilePackage/redirect?token=IscVer3xY2TgiM1SHXdse39zVUK3x0GPrIAWE4QSWt%2FXUivP2T5bITFy6VsNfCFZpmioiw%2FZoRwUTX7LssE7xBE3Jj3wcoyagS%2FzAlsE%2BJcrD6UBHASxczuh2vs1brxI5hoNOLV%2BdoFNmkumEdLEiA%3D%3D

So if you shake on the home screen and select Send Feedback, all is good. If you select the map page and shake and select send feedback, the app will crash.

I would have thought, even if the issue was something with maps not letting screenshots, at worst an error or warning should be thrown. Completely crashing seems a bad experience. 

JMTC

Note: I should have noted in original logging of the issue that I had only tried this on Android.

**Comment by mollyfud** [comment]
Any thoughts?

**Comment by EddyVerbruggen** [comment]
As I understood we shouldn't have this issue anymore.
