### ISSUE TITLE
feeback api crashes application in android device

### ISSUE THREAD

**Issue by saikatganguly** [Telerik-Verified-Plugins/Telerik-AppFeedback#2]
Hello,

Recently I encountered an issue in Android device while accessing feedback api via shaking or on button click, a popup opens with feedback options, but when click on any one of them my application is crashed with an alert 'Unfortunately App stops working'. Its working perfectly fine before.
I have tested sample app for feedback api in android and its working, I don't know what i am doing wrong in my app and why its crashing.
Here's my code  -Recently I encountered an issue in Android device while accessing feedback api via shaking or on button click, a popup opens with feedback options, but when click on any one of them my application is crashed with an alert 'Unfortunately App stops working'. Its working perfectly fine before.
I have tested sample app for feedback api in android and its working, I don't know what i am doing wrong in my app and why its crashing.
Here's my code  -

```
          <a class="nav-button hidefeedbackbtn" data-align="right" data-role="button" onclick="sendFeedback()">Feedback</a> 
```

app.js in which I initialized feedback api

(function (global) {

```
var APPFEEDBACK_API_KEY = 'ea35ad70-f2bb-11e4-83ad-a764fd037f71';


// this function is called by Cordova when the application is loaded by the device
document.addEventListener('deviceready', function () {


    var feedbackOptions = {
            enableShake: true
    };
    try {
        console.log("analytics");
        feedback.initialize(APPFEEDBACK_API_KEY, feedbackOptions);
        window.analytics.Start();
    }
    catch(err) {
        console.log('Something went wrong:');
        console.log(err);
    }

  navigator.splashscreen.hide();


  app = new kendo.mobile.Application(document.body, {
    // comment out the following line to get a UI which matches the look
    // and feel of the operating system
    skin: 'flat',
    // the application needs to know which view to load first
    initial: 'views/splash.html'
  });
    document.addEventListener("backbutton", onBackButton, true);

     }, false);
   })(window);

    function sendFeedback() {

              feedback.showFeedback();
     };
```

Thanks & regards,

Saikat

**Comment by EddyVerbruggen** [comment]
This should all be fine now.
