### ISSUE TITLE
Cordova/UIDevice+Extensions.h file not found     #import <Cordova/UIDevice+Extensions.h>

### ISSUE THREAD

**Issue by virtualprodigy** [Telerik-Verified-Plugins/Telerik-AppFeedback#7]
Whenever I try and build my project with the lastest version of the plugin I get an error Cordova/UIDevice+Extensions.h file not found     #import <Cordova/UIDevice+Extensions.h>
in xcode. 
<img width="878" alt="screen shot 2016-07-12 at 2 22 49 pm" src="https://cloud.githubusercontent.com/assets/3647217/16778511/533cd556-483c-11e6-9d5b-657c1f1b3e1f.png">

**Comment by EddyVerbruggen** [comment]
Hi, which version are you using? That code has been replaced since version 2.0.1.

**Comment by virtualprodigy** [comment]
I'm using the lastest version. I deleted it from my project and tried re-adding it.

**Comment by EddyVerbruggen** [comment]
Hmm, check [this](https://github.com/Telerik-Verified-Plugins/Telerik-AppFeedback/blob/master/src/ios/TLRKFeedback.m#L9) and compare to your screenshot. Makes me wonder how exactly you're installing it. Can you share that?

**Comment by virtualprodigy** [comment]
Is your project native or an hybrid application? I'm instating using cordova, pre the instruction on the Telerik Market Verified Market.

**Comment by EddyVerbruggen** [comment]
The latest version [there](http://plugins.telerik.com/cordova/plugin/telerik-appfeedback) is 2.0.1 which no longer has this ploblem. Can you please check which plugin version you're using?

**Comment by virtualprodigy** [comment]
I have version 2.0.2. I believe the file may have been mistakenly edited. 
![screen shot 2016-07-12 at 3 07 27 pm](https://cloud.githubusercontent.com/assets/3647217/16779937/5f54e166-4842-11e6-9b5a-fe9b887a685f.png)
